// Chioma Portfolio — Main JS
// Nav toggle, portfolio filters, lightbox, etc.

// Nav/motion/form setup doesn't depend on photos, so it runs immediately
// rather than waiting on the manifest fetch below. Everything that reads
// or builds from real photos (the portfolio grid, the homepage teaser,
// the hero polaroid stack, the page-header photo pool) waits for
// loadImageManifest() to resolve, then — if the fetch succeeded — gets a
// chance to rebuild its DOM from real folder contents before the
// filter/lightbox/ripple wiring runs against the final markup. If the
// fetch fails (e.g. opened via file:// instead of a local server — see
// PROJECT_NOTES.md), every one of those sections just keeps whatever static
// HTML is already committed in the page, so the site never goes blank.
document.addEventListener('DOMContentLoaded', async () => {
  initIntroSkip();
  initNavToggle();
  initTypewriter();
  initStickyNav();
  initFooterForm();
  initOfferCopy();

  const manifest = await loadImageManifest();
  if (manifest) {
    buildPolaroidCards(manifest);
    buildHomeTeaser(manifest);
    buildPortfolioGrid(manifest);
    buildBrandGallery(manifest);
  }

  initPolaroidStack();
  initHeaderPhoto(manifest);
  initPortfolioFilters();
  initLightbox();
  initRipples();
  initScrollReveal();
  initHeartCycle();
  initHeartZoom();
});

// ==========================================================================
// Image manifest — reads images/portfolio/manifest.json (generated by
// scripts/build-image-manifest.py from the real images/portfolio/<category>/
// folders) and uses it to build every photo-driven section of the site, so
// adding a photo to a folder and re-running that script is enough to make
// it show up everywhere relevant — no HTML/JS edits. See that script's own
// header comment for exactly how to add a new category or a nicer caption.
// ==========================================================================

// Root pages (index.html, portfolio.html, etc.) and brands/*.html pages
// are at different folder depths, so every image src/fetch path this file
// builds needs the same relative-path prefix the nav/footer markup
// already uses. Read directly off the page's own stylesheet link rather
// than hard-coding a depth check, so this keeps working if a page ever
// moves.
function assetRootPrefix() {
  const link = document.querySelector('link[rel="stylesheet"][href*="css/style.css"]');
  const href = link ? link.getAttribute('href') || '' : '';
  return href.startsWith('../') ? '../' : '';
}

async function loadImageManifest() {
  const prefix = assetRootPrefix();
  try {
    const res = await fetch(`${prefix}images/portfolio/manifest.json`, { cache: 'no-cache' });
    if (!res.ok) throw new Error(`manifest fetch returned ${res.status}`);
    return await res.json();
  } catch (err) {
    console.warn('Image manifest unavailable — keeping the page\'s static fallback content. (Opened via file:// instead of a local server? See PROJECT_NOTES.md.)', err);
    return null;
  }
}

function manifestCategoryOrder(manifest) {
  return manifest.categoryOrder && manifest.categoryOrder.length
    ? manifest.categoryOrder
    : Object.keys(manifest.categories).sort();
}

function categoryLabel(category) {
  return category
    .split(/[-_]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(' ');
}

// Portfolio page: builds both the filter-pill row and the contact-sheet
// grid from the manifest, in the exact markup/data-attribute shape
// initPortfolioFilters()/initLightbox() already expect — so those two
// functions need zero changes, they just need to run after this one.
function buildPortfolioGrid(manifest) {
  const filtersEl = document.querySelector('.portfolio-filters');
  const gridEl = document.querySelector('.portfolio-grid');
  if (!filtersEl || !gridEl) return;

  const prefix = assetRootPrefix();
  const order = manifestCategoryOrder(manifest);

  filtersEl.innerHTML = '';
  const allBtn = document.createElement('button');
  allBtn.dataset.filter = 'all';
  allBtn.className = 'active';
  allBtn.textContent = 'All';
  filtersEl.appendChild(allBtn);

  order.forEach((category) => {
    const btn = document.createElement('button');
    btn.dataset.filter = category;
    btn.textContent = categoryLabel(category);
    filtersEl.appendChild(btn);
  });

  gridEl.innerHTML = '';
  order.forEach((category) => {
    const label = categoryLabel(category);
    (manifest.categories[category] || []).forEach((item) => {
      const tile = document.createElement('button');
      tile.type = 'button';
      tile.className = 'portfolio-item' + (item.wide ? ' portfolio-item--wide' : '');
      tile.setAttribute('data-lightbox', '');
      tile.dataset.category = category;
      tile.dataset.label = label;
      tile.dataset.image = prefix + item.src;
      tile.dataset.caption = item.caption;

      const img = document.createElement('img');
      img.src = prefix + item.src;
      img.alt = item.alt;
      img.loading = 'lazy';
      if (item.cropPosition) img.style.objectPosition = item.cropPosition;
      tile.appendChild(img);

      const tag = document.createElement('span');
      tag.className = 'work-tag';
      tag.textContent = label;
      tile.appendChild(tag);

      const view = document.createElement('span');
      view.className = 'portfolio-item-view';
      view.textContent = 'View';
      tile.appendChild(view);

      gridEl.appendChild(tile);
    });
  });
}

// Homepage "A portfolio in progress" teaser — the heart frames.
// buildHomeTeaser() fills every heart with a random, non-repeating pick
// from the whole manifest on each page load (all categories pooled), and
// initHeartCycle() then keeps swapping one heart at a time to a photo
// not currently on screen. The heart markup itself (sizes, rotations,
// the desktop-only c/d/e extras) stays hand-built in index.html.
//
// Crops: `item.cropPosition` is tuned for the Portfolio grid's tiles,
// not these near-square hearts, so it's deliberately not used here.
// Heart-specific crops still live as inline object-position styles on
// the static image elements in index.html — collectHeartCrops() reads those
// once, keyed by photo, so a tuned crop follows its photo into
// whichever heart it lands in rather than staying stuck to a slot.
let heartPool = [];
const heartCrops = new Map();

function collectHeartCrops() {
  document.querySelectorAll('.work-panel-photo img').forEach((img) => {
    const pos = img.style.objectPosition;
    const src = (img.getAttribute('src') || '').replace(/^(\.\.\/)+/, '');
    if (pos) heartCrops.set(src, pos);
  });
}

function shuffle(list) {
  const a = [...list];
  for (let i = a.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function applyHeartPhoto(panel, entry, img) {
  const { item, category } = entry;
  img.src = assetRootPrefix() + item.src;
  img.alt = item.alt;
  img.dataset.caption = item.caption || item.alt;
  img.style.objectPosition = heartCrops.get(item.src) || '';
  panel.dataset.src = item.src;
  const tag = panel.querySelector('.work-tag');
  if (tag) tag.textContent = categoryLabel(category);
}

function buildHomeTeaser(manifest) {
  const panels = [...document.querySelectorAll('.work-panel')];
  if (!panels.length) return;
  collectHeartCrops();
  heartPool = manifestCategoryOrder(manifest).flatMap((category) =>
    (manifest.categories[category] || []).map((item) => ({ category, item })));
  if (heartPool.length < panels.length) return;

  const picks = shuffle(heartPool);
  panels.forEach((panel, i) => {
    const img = panel.querySelector('.work-panel-photo img');
    if (img) applyHeartPhoto(panel, picks[i], img);
  });
}

// Swaps one visible heart every few seconds to a photo that isn't on
// any heart right now, crossfading the new image in over the old one.
// Runs only while the section is on screen and the tab is visible; the
// heart currently zoomed open (see initHeartZoom) is left alone. Off
// under reduced motion — the hearts keep their random load-time picks.
const HEART_SWAP_MS = 3200;

function initHeartCycle() {
  const grid = document.querySelector('.work-grid');
  if (!grid || heartPool.length < 2) return;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  let inView = false;
  let lastPanel = null;
  new IntersectionObserver(([entry]) => { inView = entry.isIntersecting; }).observe(grid);

  setInterval(() => {
    if (!inView || document.hidden) return;
    const all = [...grid.querySelectorAll('.work-panel')];
    const candidates = all.filter((p) => p.offsetParent !== null && !p.classList.contains('is-zoomed') && p !== lastPanel);
    if (!candidates.length) return;
    const panel = candidates[Math.floor(Math.random() * candidates.length)];
    const showing = new Set(all.map((p) => p.dataset.src));
    const options = heartPool.filter((e) => !showing.has(e.item.src));
    if (!options.length) return;
    lastPanel = panel;
    swapHeartPhoto(panel, options[Math.floor(Math.random() * options.length)]);
  }, HEART_SWAP_MS);
}

function swapHeartPhoto(panel, entry) {
  const layer = panel.querySelector('.work-panel-photo');
  const oldImg = layer && layer.querySelector('img:last-of-type');
  if (!oldImg) return;
  const img = document.createElement('img');
  img.className = 'is-entering';
  img.draggable = false;
  applyHeartPhoto(panel, entry, img);
  oldImg.after(img);
  // Wait for the new photo to decode so the fade never reveals a blank
  // heart, then drop the old image once the crossfade has finished.
  (img.decode ? img.decode() : Promise.resolve()).catch(() => {}).then(() => {
    void img.offsetWidth; // commit the hidden state so the fade runs
    img.classList.remove('is-entering');
    setTimeout(() => oldImg.remove(), 1000);
  });
}

// Tap/click (or Enter/Space) a heart: a copy of it lifts out of the
// page and grows to the middle of the screen over a dimmed backdrop,
// then opens out into the whole uncropped photo (the heart shape crops
// a lot) with its caption beneath; after a beat it folds back into the
// heart, which shrinks back into its slot and the original reappears. Tap again, tap the
// backdrop, or press Escape to send it back early.
//
// The copy is built at its FINAL (large) size and animated from a
// scaled-down transform to none — so it ends at native resolution and
// stays sharp, rather than upscaling a small rasterized heart.
const HEART_HOLD_MS = 4500;

function initHeartZoom() {
  const panels = document.querySelectorAll('.work-panel');
  if (!panels.length) return;
  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  let open = null;

  panels.forEach((panel) => {
    panel.setAttribute('role', 'button');
    panel.setAttribute('tabindex', '0');
    panel.setAttribute('aria-label', 'Enlarge photo');
    panel.addEventListener('click', () => (open ? open.close() : zoom(panel)));
    panel.addEventListener('keydown', (e) => {
      if (e.key !== 'Enter' && e.key !== ' ') return;
      e.preventDefault();
      if (open) open.close(); else zoom(panel);
    });
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && open) open.close();
  });

  function zoom(panel) {
    const frame = panel.querySelector('.work-panel-frame');
    const srcImg = panel.querySelector('.work-panel-photo img:last-of-type');
    if (!frame || !srcImg) return;

    const rect = frame.getBoundingClientRect();
    const baseW = frame.offsetWidth;
    const m = new DOMMatrixReadOnly(getComputedStyle(frame).transform);
    const rot = Math.atan2(m.b, m.a) * (180 / Math.PI);

    const targetW = Math.min(window.innerWidth * 0.86, window.innerHeight * 0.62 * 1.08, 560);
    const scale = baseW / targetW;
    const offset = (r) => `translate(${r.left + r.width / 2 - window.innerWidth / 2}px, ${r.top + r.height / 2 - window.innerHeight / 2}px) rotate(${rot}deg) scale(${scale})`;
    // The pink rim is a fixed 10px on the small heart; keep it the same
    // proportion of the big one so the frame doesn't thin out.
    const rim = 10 / scale;

    // The uncropped photo the heart opens into: the whole image at its
    // own aspect ratio, as large as fits the screen (leaving room for
    // the caption below), so nothing the heart's shape cut off stays
    // hidden.
    const ratio = srcImg.naturalWidth && srcImg.naturalHeight
      ? srcImg.naturalWidth / srcImg.naturalHeight
      : 3 / 4;
    const maxW = Math.min(window.innerWidth * 0.9, 760);
    const maxH = window.innerHeight * 0.7;
    const fullW = Math.min(maxW, maxH * ratio);
    const fullH = fullW / ratio;

    const overlay = document.createElement('div');
    overlay.className = 'heart-zoom';
    overlay.innerHTML = `
      <div class="heart-zoom-scrim"></div>
      <figure class="heart-zoom-stage">
        <div class="heart-zoom-heart" style="width:${targetW}px">
          <div class="work-panel-accent" style="inset:-${rim}px"></div>
          <div class="work-panel-photo"><img alt=""></div>
        </div>
        <div class="heart-zoom-full" style="width:${fullW}px;height:${fullH}px">
          <img alt="">
          <figcaption class="heart-zoom-caption"></figcaption>
        </div>
      </figure>`;
    const [heartImg, fullImg] = overlay.querySelectorAll('img');
    heartImg.src = srcImg.src;
    heartImg.style.objectPosition = srcImg.style.objectPosition;
    fullImg.src = srcImg.src;
    fullImg.alt = srcImg.alt;
    overlay.querySelector('.heart-zoom-caption').textContent = srcImg.dataset.caption || srcImg.alt;
    document.body.appendChild(overlay);

    const heart = overlay.querySelector('.heart-zoom-heart');
    const timing = { duration: reduceMotion ? 1 : 750, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', fill: 'both' };

    // Two beats: the heart flies forward to the center, then — just
    // before it settles — opens out into the full photo (CSS crossfade
    // on .is-full: heart fades/swells away, full photo scales up into
    // place).
    panel.classList.add('is-zoomed');
    heart.animate([{ transform: offset(rect) }, { transform: 'none' }], timing);
    void overlay.offsetWidth; // commit the closed state so the fade runs
    overlay.classList.add('is-open');
    const fullTimer = setTimeout(() => overlay.classList.add('is-full'), reduceMotion ? 0 : 520);

    let closing = false;
    const holdTimer = setTimeout(close, HEART_HOLD_MS);
    overlay.addEventListener('click', close);

    function close() {
      if (closing) return;
      closing = true;
      clearTimeout(holdTimer);
      clearTimeout(fullTimer);
      // Reverse the two beats: fold the full photo back into the heart,
      // then fly the heart home.
      const wasFull = overlay.classList.contains('is-full');
      overlay.classList.remove('is-full');
      setTimeout(flyHome, wasFull && !reduceMotion ? 380 : 0);
    }

    function flyHome() {
      overlay.classList.remove('is-open');
      // Re-measure: the heart's float animation (or a scroll) may have
      // moved its slot while it was open.
      const back = offset(frame.getBoundingClientRect());
      const duration = reduceMotion ? 1 : 600;
      const anim = heart.animate([{ transform: 'none' }, { transform: back }], { ...timing, duration });
      // Belt and braces: if the animation never reports finishing (e.g.
      // the tab was backgrounded mid-close), tidy up on a timer anyway
      // so a heart can never get stuck hidden.
      let done = false;
      const finish = () => {
        if (done) return;
        done = true;
        panel.classList.remove('is-zoomed');
        overlay.remove();
        open = null;
      };
      anim.onfinish = finish;
      setTimeout(finish, duration + 250);
    }

    open = { close };
  }
}

// Brand pages' "Campaign Preview" row: if images/brands/<this page's
// name>/ has photos (manifest "brands" key, see
// scripts/build-image-manifest.py), they replace the placeholder swatch
// tiles — up to six. No photos yet, or no manifest: the swatches stay.
const BRAND_GALLERY_MAX = 6;

function buildBrandGallery(manifest) {
  const grid = document.querySelector('.brand-gallery-grid');
  if (!grid || !manifest.brands) return;
  const slug = (window.location.pathname.split('/').pop() || '').replace(/\.html$/, '');
  const items = (manifest.brands[slug] || []).slice(0, BRAND_GALLERY_MAX);
  if (!items.length) return;

  const prefix = assetRootPrefix();
  grid.innerHTML = '';
  items.forEach((item) => {
    const tile = document.createElement('div');
    tile.className = 'gallery-tile';
    const img = document.createElement('img');
    img.src = prefix + item.src;
    img.alt = item.alt;
    img.loading = 'lazy';
    if (item.cropPosition) img.style.objectPosition = item.cropPosition;
    tile.appendChild(img);
    grid.appendChild(tile);
  });
  const note = grid.parentElement.querySelector('.work-note');
  if (note) note.hidden = true;
}

// Hero polaroid stack — rebuilds the card list from up to two photos per
// category (interleaved by category, not grouped) so the stack still
// alternates fashion/beauty/lifestyle/... the way the hand-built version
// did, rather than clustering every photo from one category together.
// Leaves the stack's existing static cards untouched if the manifest
// has fewer than 2 usable photos, so the no-JS/fetch-failure fallback
// (see the CSS nth-child rules this component falls back to) still has
// something real to show.
function buildPolaroidCards(manifest) {
  const stack = document.querySelector('[data-polaroid-stack]');
  if (!stack) return;

  const prefix = assetRootPrefix();
  const order = manifestCategoryOrder(manifest);
  const PER_CATEGORY = 2;
  const MAX_CARDS = 6;

  const picks = [];
  for (let round = 0; round < PER_CATEGORY; round += 1) {
    order.forEach((category) => {
      const items = manifest.categories[category];
      if (items && items[round]) picks.push({ category, item: items[round] });
    });
  }
  const chosen = picks.slice(0, MAX_CARDS);
  if (chosen.length < 2) return;

  stack.innerHTML = '';
  chosen.forEach(({ category, item }) => {
    const card = document.createElement('div');
    card.className = 'polaroid-card';
    card.setAttribute('data-polaroid-card', '');

    const img = document.createElement('img');
    img.src = prefix + item.src;
    img.alt = item.alt;
    img.draggable = false;
    card.appendChild(img);

    const caption = document.createElement('span');
    caption.className = 'polaroid-caption';
    caption.textContent = categoryLabel(category);
    card.appendChild(caption);

    stack.appendChild(card);
  });
}

// Footer "quick message" form — the site is static with no backend (see
// PRODUCT.md), so this can't silently POST anywhere; it builds a mailto:
// link from the three fields and hands off to the visitor's own mail
// client instead, which is genuinely functional without needing a
// third-party form service. Shows a brief confirmation note rather than
// just silently redirecting, since handing off to mailto: can otherwise
// look like nothing happened if the OS is slow to switch apps.
function initFooterForm() {
  const form = document.querySelector('.footer-form');
  if (!form) return;
  const note = form.querySelector('.footer-form-note');
  form.addEventListener('submit', (e) => {
    e.preventDefault();
    const name = form.elements.name.value.trim();
    const email = form.elements.email.value.trim();
    const message = form.elements.message.value.trim();
    const subject = encodeURIComponent(`Inquiry from ${name}`);
    const body = encodeURIComponent(`${message}\n\n— ${name} (${email})`);
    window.location.href = `mailto:chioma@azhyre.co.za?subject=${subject}&body=${body}`;
    if (note) {
      note.textContent = "Opening your email app to send this — if nothing happens, email chioma@azhyre.co.za directly.";
    }
  });
}

// Header sizing/visibility on scroll, matching .site-nav's .is-compact/
// .is-shadow/.is-hidden classes in style.css: fully grown (no class) only
// at the very top; .is-compact (shrunk) any time scrollY > 0, whether
// scrolling up or down, so the header stays shrunk-but-visible on the way
// back up instead of growing back to a mid-size first. .is-shadow lifts
// the header off the page any time it isn't at that resting top
// position, so it reads as hovering above passing content rather than
// flush with it. .is-hidden (desktop only — no-op at ≤900px, see
// responsive.css) is direction-aware, unlike the other two: added while
// actively scrolling down (so the fixed, hero-overlaying header doesn't
// sit over content indefinitely), removed the instant the user scrolls
// up even slightly, and always cleared at the very top. rAF-throttled so
// this never runs more than once per paint.
function initStickyNav() {
  const nav = document.querySelector('.site-nav');
  if (!nav) return;

  let lastY = window.scrollY;
  let ticking = false;

  function update() {
    const y = window.scrollY;
    if (y <= 0) {
      nav.classList.remove('is-compact', 'is-shadow', 'is-hidden');
    } else {
      nav.classList.add('is-compact', 'is-shadow');
      if (y > lastY) {
        nav.classList.add('is-hidden');
      } else {
        nav.classList.remove('is-hidden');
      }
    }
    lastY = y;
    ticking = false;
  }

  window.addEventListener('scroll', () => {
    if (!ticking) {
      window.requestAnimationFrame(update);
      ticking = true;
    }
  }, { passive: true });

  update();
}

// Page-header photo (About/Portfolio/Brands/Contact masthead) — picks one
// photo at random from the full image manifest on each load, so the
// page/photo pairing isn't fixed and every photo in every category is
// eligible (not a hand-curated subset — see PROJECT_NOTES.md for why
// this pool used to be curated down and what changed). If the manifest
// didn't load, or this page has no [data-header-photo] element, leaves
// whatever src/alt is already hard-coded in the HTML untouched.
function initHeaderPhoto(manifest) {
  const img = document.querySelector('[data-header-photo]');
  if (!img || !manifest) return;
  const prefix = assetRootPrefix();
  const pool = manifestCategoryOrder(manifest).flatMap((category) => manifest.categories[category] || []);
  if (!pool.length) return;
  const choice = pool[Math.floor(Math.random() * pool.length)];
  img.src = prefix + choice.src;
  img.alt = choice.alt;
  img.style.objectPosition = choice.cropPosition || '';
}

// Continuously cycles the hero wordmark through WORDS — typing each in,
// holding, then erasing before typing the next — forever, not a one-shot
// reveal. Each new letter is a fresh <span class="letter"> given an
// .is-in class one frame after insertion so its opacity/transform
// transition actually has something to animate from (same double-rAF
// pattern initPortfolioFilters uses). Erasing mirrors that: it removes
// the .is-in class (triggering the same transition in reverse) and only
// detaches the span from the DOM after that transition would have
// finished, so backspacing reads as a smooth cascade rather than an
// abrupt snap — `liveLetters` (not the DOM's own childElementCount) is
// what tracks "how many letters are logically left," since erase ticks
// fire faster than each individual fade-out finishes and several spans
// end up mid-fade in the DOM at once. Per-letter typing speed is
// randomized within a range for an organic, non-mechanical feel. Skipped
// entirely under reduced motion — the plain "Chioma" text the original
// markup already had stays fully visible and static, matching every
// other motion effect on this site.
function initTypewriter() {
  const el = document.querySelector('.hero-title .typewriter');
  if (!el || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  const WORDS = ['Chioma', 'Miyelani', 'Anieze'];

  const TYPE_MS_MIN = 70;
  const TYPE_MS_MAX = 130;
  const ERASE_MS = 45;
  const ERASE_FADE_MS = 230; // matches .hero-title .letter's transition duration
  const HOLD_FULL_MS = 1400;
  const HOLD_EMPTY_MS = 350;
  const START_DELAY_MS = 300;

  el.innerHTML = '';
  const caret = document.createElement('span');
  caret.className = 'caret';
  el.after(caret);

  let wordIndex = 0;
  let len = 0;
  let typing = true;
  const liveLetters = [];

  function currentWord() {
    return WORDS[wordIndex];
  }

  function addLetter() {
    const word = currentWord();
    const span = document.createElement('span');
    span.className = len === word.length - 1 ? 'letter accent' : 'letter';
    span.textContent = word[len];
    el.appendChild(span);
    liveLetters.push(span);
    len += 1;
    requestAnimationFrame(() => {
      requestAnimationFrame(() => span.classList.add('is-in'));
    });
  }

  function removeLetter() {
    const span = liveLetters.pop();
    if (!span) return;
    len -= 1;
    span.classList.remove('is-in');
    window.setTimeout(() => span.remove(), ERASE_FADE_MS);
  }

  function tick() {
    if (typing) {
      addLetter();
      if (len >= currentWord().length) {
        typing = false;
        window.setTimeout(tick, HOLD_FULL_MS);
      } else {
        const jitter = TYPE_MS_MIN + Math.random() * (TYPE_MS_MAX - TYPE_MS_MIN);
        window.setTimeout(tick, jitter);
      }
    } else {
      removeLetter();
      if (len <= 0) {
        typing = true;
        wordIndex = (wordIndex + 1) % WORDS.length;
        window.setTimeout(tick, HOLD_EMPTY_MS);
      } else {
        window.setTimeout(tick, ERASE_MS);
      }
    }
  }

  window.setTimeout(tick, START_DELAY_MS);
}

// Hero "polaroid stack" — real photos standing in for the old silhouette
// placeholder, in the same slot (see the .hero-visual .polaroid-stack
// page-open animation in style.css, reused from .silhouette-frame).
// Cycling reassigns cards to a fixed set of back-of-pile scatter "slots"
// rather than re-rolling every card's own offset, so the motion reads as
// one photo sliding to the back and the next rising to front, not the
// whole pile jumping. Reshuffle (double-tap/-click, or Enter) is the only
// thing that re-rolls the slot offsets themselves. Skipped entirely (no
// autoplay, no transitions) under reduced motion, but swipe/tap/keyboard
// cycling still works — same "still operable, just not animated" pattern
// as the rest of the site's motion.
function initPolaroidStack() {
  const stack = document.querySelector('[data-polaroid-stack]');
  if (!stack) return;
  const order = Array.from(stack.querySelectorAll('[data-polaroid-card]'));
  if (order.length < 2) return;

  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const AUTO_MS = 4000;
  const SWIPE_PX = 50;
  const TAP_PX = 10;
  const DOUBLE_TAP_MS = 350;

  let slots = order.slice(1).map((_, i) => ({
    tx: (i % 2 === 0 ? 1 : -1) * (5 + i * 2),
    ty: (i % 2 === 0 ? -1 : 1) * (4 + i * 3),
    rot: (i % 2 === 0 ? 1 : -1) * (6 + i * 2),
  }));
  let autoTimer = null;
  let autoDirection = 1; // 1 = front card cycles to back; -1 = reversed
  let lastTapTime = 0;
  let dragStartX = null;

  function rollSlots() {
    slots = order.slice(1).map((_, i) => {
      const sign = i % 2 === 0 ? 1 : -1;
      return {
        tx: sign * (4 + Math.random() * 4 + i * 1.5),
        ty: (Math.random() - 0.5) * (8 + i * 3),
        rot: sign * (5 + Math.random() * 6),
      };
    });
  }

  function applyOrder(animate) {
    order.forEach((card, i) => {
      card.style.transition = animate ? '' : 'none';
      card.style.zIndex = String(order.length - i);
      if (i === 0) {
        card.style.setProperty('--tx', '0%');
        card.style.setProperty('--ty', '0%');
        card.style.setProperty('--rot', '0deg');
      } else {
        const slot = slots[i - 1];
        card.style.setProperty('--tx', `${slot.tx}%`);
        card.style.setProperty('--ty', `${slot.ty}%`);
        card.style.setProperty('--rot', `${slot.rot}deg`);
      }
    });
  }

  function cycle(direction) {
    if (direction === 1) order.push(order.shift());
    else order.unshift(order.pop());
    applyOrder(true);
  }

  function reshuffle() {
    rollSlots();
    applyOrder(true);
  }

  function stopAuto() {
    if (autoTimer) window.clearInterval(autoTimer);
    autoTimer = null;
  }

  function startAuto() {
    if (reduceMotion) return;
    stopAuto();
    autoTimer = window.setInterval(() => cycle(autoDirection), AUTO_MS);
  }

  applyOrder(false);
  void stack.offsetWidth; // force reflow before re-enabling transitions
  order.forEach((card) => { card.style.transition = ''; });

  const io = new IntersectionObserver(([entry]) => {
    if (entry.isIntersecting) startAuto();
    else stopAuto();
  }, { threshold: 0.2 });
  io.observe(stack);

  function endDrag(dx) {
    order[0].style.transition = '';
    order[0].style.setProperty('--drag', '0px');
    dragStartX = null;

    if (Math.abs(dx) < TAP_PX) {
      const now = Date.now();
      if (now - lastTapTime < DOUBLE_TAP_MS) {
        reshuffle();
        lastTapTime = 0;
      } else {
        lastTapTime = now;
      }
    } else if (Math.abs(dx) >= SWIPE_PX) {
      autoDirection = dx < 0 ? 1 : -1;
      cycle(autoDirection);
    }
    startAuto();
  }

  stack.addEventListener('pointerdown', (e) => {
    dragStartX = e.clientX;
    stopAuto();
    order[0].style.transition = 'none';
  });

  stack.addEventListener('pointermove', (e) => {
    if (dragStartX === null) return;
    order[0].style.setProperty('--drag', `${e.clientX - dragStartX}px`);
  });

  stack.addEventListener('pointerup', (e) => {
    if (dragStartX === null) return;
    endDrag(e.clientX - dragStartX);
  });

  stack.addEventListener('pointercancel', () => {
    if (dragStartX === null) return;
    endDrag(0);
  });

  stack.addEventListener('keydown', (e) => {
    if (e.key === 'ArrowLeft') {
      e.preventDefault();
      autoDirection = -1;
      cycle(-1);
      startAuto();
    } else if (e.key === 'ArrowRight') {
      e.preventDefault();
      autoDirection = 1;
      cycle(1);
      startAuto();
    } else if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      reshuffle();
      startAuto();
    }
  });
}

// Tactile click/tap feedback on solid buttons, filter pills, and
// portfolio tiles. Skipped entirely under reduced motion, and skipped
// for keyboard activation (no pointer coordinate, no visual to anchor).
const RIPPLE_SELECTOR = '.btn-primary, .portfolio-filters button, .portfolio-item, .lightbox-close, .nav-toggle';

function createRipple(x, y, el) {
  const rect = el.getBoundingClientRect();
  const size = Math.max(rect.width, rect.height) * 2;
  const span = document.createElement('span');
  span.className = 'ripple';
  span.style.width = `${size}px`;
  span.style.height = `${size}px`;
  span.style.left = `${x - rect.left - size / 2}px`;
  span.style.top = `${y - rect.top - size / 2}px`;
  el.appendChild(span);
  span.addEventListener('animationend', () => span.remove());
}

function attachRipple(el) {
  el.classList.add('ripple-surface');
  el.addEventListener('pointerdown', (e) => {
    if (e.pointerType === 'mouse' && e.button !== 0) return;
    createRipple(e.clientX, e.clientY, el);
  });
}

function initRipples() {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  document.querySelectorAll(RIPPLE_SELECTOR).forEach(attachRipple);
}

// First-visit intro (index.html): the inline <head> script decides
// whether to show it and lifts it on its own timer; this only lets a
// tap/click or key press lift it early.
function initIntroSkip() {
  const intro = document.querySelector('.site-intro');
  const root = document.documentElement;
  if (!intro || !root.classList.contains('show-intro')) return;
  const lift = () => root.classList.remove('show-intro');
  intro.addEventListener('click', lift);
  document.addEventListener('keydown', lift, { once: true });
}

// Scroll reveal: content below the masthead eases in as it scrolls into
// view, one magazine page at a time. Elements opt in by matching
// REVEAL_SELECTOR (tagged here, so no per-page markup is needed) or by
// carrying a hand-placed .reveal class. Siblings revealed together get a
// short stagger. Ghost words get their own slower side-slide. Nothing is
// hidden until this runs (.reveal-armed is only added by JS), so with JS
// off or under reduced motion every element simply stays visible.
const REVEAL_SELECTOR = [
  '.section-kicker', 'main .kicker', 'main h2',
  '.work-intro p', '.about-copy', '.work-cta',
  '.focus-item', '.brand-row a', '.glance-item', '.bio-copy p',
  '.contact-block', '.brand-index-row', '.gallery-tile',
  '.footer-top > *'
].join(', ');

function initScrollReveal() {
  if (!('IntersectionObserver' in window)) return;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  document.querySelectorAll(REVEAL_SELECTOR).forEach((el) => {
    // The masthead has its own authored entrance; and anything already
    // inside a revealing container would just double-animate.
    if (el.closest('.hero, .page-header')) return;
    if (el.parentElement.closest('.reveal')) return;
    el.classList.add('reveal');
  });

  const targets = [...document.querySelectorAll('.reveal, .ghost-word')];
  targets.forEach((el) => {
    // Stagger among revealed siblings (cards in a row, brand names…),
    // capped so a long list doesn't make the last item wait forever.
    const siblings = [...el.parentElement.children].filter((c) => c.classList.contains('reveal'));
    const index = Math.min(siblings.indexOf(el), 4);
    if (index > 0) el.style.setProperty('--reveal-delay', `${index * 110}ms`);
    el.classList.add('reveal-armed');
  });

  const io = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add('is-visible');
      io.unobserve(entry.target);
    });
  }, { rootMargin: '0px 0px -12% 0px' });

  targets.forEach((el) => io.observe(el));
}

// Mobile off-canvas drawer: toggling .nav-collapse now also toggles a
// .nav-scrim backdrop (both elements, not just the drawer, since the
// scrim is a separate fixed sibling that dims the rest of the page
// while the drawer is open). Closes on scrim click or Escape, in
// addition to the toggle button itself.
function initNavToggle() {
  const toggle = document.querySelector('.nav-toggle');
  const collapse = document.querySelector('.nav-collapse');
  const scrim = document.querySelector('.nav-scrim');
  if (!toggle || !collapse) return;

  function setOpen(isOpen) {
    collapse.classList.toggle('open', isOpen);
    if (scrim) scrim.classList.toggle('open', isOpen);
    toggle.setAttribute('aria-expanded', String(isOpen));
  }

  toggle.addEventListener('click', () => {
    setOpen(!collapse.classList.contains('open'));
  });

  if (scrim) {
    scrim.addEventListener('click', () => setOpen(false));
  }

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && collapse.classList.contains('open')) setOpen(false);
  });
}

function initPortfolioFilters() {
  const filterButtons = document.querySelectorAll('[data-filter]');
  const items = document.querySelectorAll('[data-category]');
  if (!filterButtons.length || !items.length) return;

  function setItemVisible(item, visible) {
    if (visible) {
      item.hidden = false;
      requestAnimationFrame(() => {
        requestAnimationFrame(() => item.classList.remove('is-hidden'));
      });
    } else {
      item.classList.add('is-hidden');
      window.setTimeout(() => {
        item.hidden = true;
      }, 350);
    }
  }

  filterButtons.forEach((button) => {
    button.addEventListener('click', () => {
      const filter = button.dataset.filter;

      items.forEach((item) => {
        const show = filter === 'all' || item.dataset.category === filter;
        setItemVisible(item, show);
      });

      filterButtons.forEach((b) => b.classList.remove('active'));
      button.classList.add('active');
    });
  });
}

// Portfolio lightbox — a contact-sheet viewer, not a single-photo popup:
// opens on the tapped tile, then steps through every tile currently
// visible in the grid (so a category filter also filters what you can
// page through) with ‹ › buttons, arrow keys, or a horizontal swipe,
// wrapping at either end. A film-negative "03 / 15" counter matches the
// grid's frame numbers. Photos are shown whole (object-fit: contain),
// never cropped. Neighbours are preloaded so stepping feels instant.
function initLightbox() {
  const grid = document.querySelector('.portfolio-grid');
  const overlay = document.querySelector('.lightbox-overlay');
  const stage = overlay ? overlay.querySelector('.lightbox-content') : null;
  if (!grid || !overlay || !stage) return;

  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  let lastTrigger = null;
  let sequence = [];
  let index = 0;

  // Built once; open()/show() only swap its contents.
  stage.innerHTML = `
    <button type="button" class="lightbox-close" aria-label="Close">&times;</button>
    <div class="lightbox-panel">
      <span class="work-tag"></span>
    </div>
    <button type="button" class="lightbox-nav lightbox-nav--prev" aria-label="Previous photo">&lsaquo;</button>
    <button type="button" class="lightbox-nav lightbox-nav--next" aria-label="Next photo">&rsaquo;</button>
    <div class="lightbox-meta">
      <p class="lightbox-counter" aria-live="polite"></p>
      <p class="lightbox-caption"></p>
    </div>`;
  const closeBtn = stage.querySelector('.lightbox-close');
  const panel = stage.querySelector('.lightbox-panel');
  const tag = panel.querySelector('.work-tag');
  const counter = stage.querySelector('.lightbox-counter');
  const caption = stage.querySelector('.lightbox-caption');
  const prevBtn = stage.querySelector('.lightbox-nav--prev');
  const nextBtn = stage.querySelector('.lightbox-nav--next');
  if (!reduceMotion) [closeBtn, prevBtn, nextBtn].forEach(attachRipple);

  const pad = (n) => String(n).padStart(2, '0');

  function visibleTiles() {
    return [...grid.querySelectorAll('[data-lightbox]')]
      .filter((t) => !t.hidden && !t.classList.contains('is-hidden'));
  }

  function preload(i) {
    const t = sequence[(i + sequence.length) % sequence.length];
    if (t && t.dataset.image) new Image().src = t.dataset.image;
  }

  function show(i, direction = 0) {
    index = (i + sequence.length) % sequence.length;
    const trigger = sequence[index];
    const triggerImg = trigger.querySelector('img');

    const oldImg = panel.querySelector('img:not(.is-leaving)');
    const img = document.createElement('img');
    img.src = trigger.dataset.image || '';
    img.alt = triggerImg ? triggerImg.alt : '';
    img.draggable = false;
    if (!reduceMotion && direction) {
      img.className = 'is-entering';
      img.style.setProperty('--from', `${direction * 6}%`);
    }
    panel.insertBefore(img, tag);
    if (oldImg) {
      oldImg.classList.add('is-leaving');
      oldImg.style.setProperty('--to', `${direction * -6}%`);
      setTimeout(() => oldImg.remove(), reduceMotion ? 0 : 450);
    }
    void img.offsetWidth; // commit the entering state so the slide runs
    img.classList.remove('is-entering');

    tag.textContent = trigger.dataset.label || trigger.dataset.category || '';
    tag.hidden = !tag.textContent;
    caption.textContent = trigger.dataset.caption || '';
    counter.textContent = `${pad(index + 1)} / ${pad(sequence.length)}`;
    const single = sequence.length < 2;
    prevBtn.hidden = single;
    nextBtn.hidden = single;
    preload(index + 1);
    preload(index - 1);
  }

  function open(trigger) {
    lastTrigger = trigger;
    sequence = visibleTiles();
    if (!sequence.includes(trigger)) sequence = [trigger];
    panel.querySelectorAll('img').forEach((im) => im.remove());
    show(sequence.indexOf(trigger));
    overlay.classList.add('is-open');
    overlay.setAttribute('aria-hidden', 'false');
    document.body.style.overflow = 'hidden';
    closeBtn.focus();
  }

  function close() {
    overlay.classList.remove('is-open');
    overlay.setAttribute('aria-hidden', 'true');
    document.body.style.overflow = '';
    if (lastTrigger) lastTrigger.focus();
  }

  const step = (d) => show(index + d, d);

  // Delegated so tiles rebuilt from the manifest (buildPortfolioGrid)
  // are covered without re-binding.
  grid.addEventListener('click', (e) => {
    const trigger = e.target.closest('[data-lightbox]');
    if (!trigger) return;
    e.preventDefault();
    open(trigger);
  });

  closeBtn.addEventListener('click', close);
  prevBtn.addEventListener('click', () => step(-1));
  nextBtn.addEventListener('click', () => step(1));

  overlay.addEventListener('click', (e) => {
    if (e.target === overlay) close();
  });

  document.addEventListener('keydown', (e) => {
    if (!overlay.classList.contains('is-open')) return;
    if (e.key === 'Escape') close();
    else if (e.key === 'ArrowRight') step(1);
    else if (e.key === 'ArrowLeft') step(-1);
  });

  // Swipe: a mostly-horizontal drag of 50px+ on the photo steps; anything
  // else (a tap, a vertical scroll attempt) is ignored.
  let startX = null;
  let startY = null;
  panel.addEventListener('pointerdown', (e) => {
    startX = e.clientX;
    startY = e.clientY;
  });
  panel.addEventListener('pointerup', (e) => {
    if (startX === null) return;
    const dx = e.clientX - startX;
    const dy = e.clientY - startY;
    startX = null;
    if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) step(dx < 0 ? 1 : -1);
  });
  panel.addEventListener('pointercancel', () => { startX = null; });
}

// Copy buttons on offers.html: copies the code from data-copy, then briefly
// shows "Copied". Falls back to showing the code when clipboard access is
// blocked (e.g. some in-app browsers), so the visitor can still read it.
function initOfferCopy() {
  document.querySelectorAll('.offer-copy').forEach((btn) => {
    const label = btn.textContent;
    btn.addEventListener('click', async () => {
      const code = btn.dataset.copy || '';
      try {
        await navigator.clipboard.writeText(code);
        btn.textContent = 'Copied';
      } catch (err) {
        btn.textContent = code;
      }
      window.setTimeout(() => { btn.textContent = label; }, 1600);
    });
  });
}
